common: &common
  adapter: postgresql
  username: [username]
  password: [password]
  pool: 5
  timeout: 5000

development:
  <<: *common
  database: [app_name]_dev

test:
  <<: *common
  database: [app_name]_test