common: &common
  adapter: postgresql
  username: tyler
  password: 123456
  pool: 5
  timeout: 5000

development:
  <<: *common
  database: rails_setup_dev

test:
  <<: *common
  database: rails_setup_test